Added redis failover. (#90)
* Added redis failover.

* Added test for Redis enable variable.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -37,6 +37,18 @@ jobs:
           command: |
             ahoy drush st
             ahoy drush pml
+      - run:
+          name: Test Redis is functional
+          command: |
+            # Set ENABLE_REDIS env var and warm cache with bootstrap.
+            docker-compose exec -T --env ENABLE_REDIS=true cli drush status
+            redisKeys=$(docker-compose exec -T redis redis-cli KEYS '*'|wc -l)
+            if [[ $redisKeys -le 1 ]];  then
+              echo "Redis fail: No valid cache keys."
+              exit 1
+            else
+              echo "Redis success: Redis contains $redisKeys keys."
+            fi
 workflows:
   version: 2
   main:
